nsacyber/paccor

scripts/get_ek.sh

Closes #6.
The EC gathering script will now parse the blob of data retrieved from the NVRAM index.  It looks for the first ASN1 sequence in the blob.  For now, it will assume EC sizes will continue to fit in that 16 bit length value. The script will truncate any bytes after the end of the declared size.
The specific index to read from is still configurable by the user.  By default, it will use the constant value recommended for an EC.

[#6] get_ek.sh removes extra bytes before and after first ASN1 sequence

---

build.gradle
scripts/get_ek.sh

[#11] get_ek.sh will now buffer reading from NVRAM on both 1.2 and 2.0.

---

build.gradle
scripts/get_ek.sh

[#12] get_ek.sh will use apt on ubuntu.

---

build.gradle
scripts/get_ek.sh

[#8] Enabled detection of TPM2 emulator if not registered into dmesg.

---

NOTICE.md
build.gradle

[#18] New packages.

---

build.gradle

[#24] 1.0.6-2

---

scripts/windows/otherextensions.ps1
scripts/windows/referenceoptions.ps1

[#32] Policy and extension scripts ported to powershell

---

scripts/windows/allcomponents.ps1
scripts/windows/get_ek.ps1
scripts/windows/pc_certgen.ps1

[#33] Ported pc_certgen to powershell

---

build.gradle
scripts/enterprise-numbers

Closes #40.
This release includes Windows support in the form of powershell scripts for pulling together certificate data.
The certificate builder, signer, and validator are still Java-based and platform-agnostic.
An application distribution can be built using the following command from the root project folder:
gradle clean build distZip
This will create a zip file in build/distributions/paccor.zip which contains binaries as well as the platform scripts.

[#40] Release v1.0.7r1

---

src/main/java/cli/DeviceObserverArgs.java
src/main/java/cli/DeviceObserverCli.java
src/main/java/cli/SigningArgs.java
src/main/java/cli/SigningCli.java
src/main/java/factory/ComponentIdentifierV2Factory.java
src/main/java/factory/PlatformCertificateFactory.java
src/main/java/factory/PlatformConfigurationV2Factory.java
src/main/java/json/OtherExtensionsJsonHelper.java
src/main/java/tcg/credential/AttributeCertificateIdentifier.java
src/main/java/tcg/credential/AttributeStatus.java
src/main/java/tcg/credential/CertificateIdentifier.java
src/main/java/tcg/credential/ComponentAddress.java
src/main/java/tcg/credential/ComponentClass.java
src/main/java/tcg/credential/ComponentIdentifierV2.java
src/main/java/tcg/credential/PlatformConfigurationV2.java
src/main/java/tcg/credential/PlatformPropertiesV2.java
src/main/java/tcg/credential/TCGObjectIdentifier.java
src/test/java/cli/DeviceObserverTest.java
src/test/java/factory/PlatformConfigurationFactoryV2Test.java
src/test/resources/comps_flawed_2187.json
src/test/resources/comps_large_2187.json
src/test/resources/comps_medium_2187.json
src/test/resources/deviceInfo.json

Closes #46, #48, #49, #50 .
Created V2 versions of all classes that would have been changed to meet new requirements of the attribute.
Updated the JSON processing for ComponentIdentifierV2.

[#46] Implemented V2 of the platform configuration attribute and JSON.

---

scripts/allcomponents.sh
scripts/otherextensions.sh
scripts/windows/allcomponents.ps1
scripts/windows/otherextensions.ps1
src/main/java/cli/DeviceObserverCli.java

Not closing #56 as I'll have a new version of the guide soon.  I want these bug fixes pushed to master.

Merging fixes for some bugs.

---

src/main/java/factory/PlatformCertificateFactory.java
src/main/java/tcg/credential/TCGObjectIdentifier.java

Closes #51.
Changed the way OIDs are constructed.

[#51] Changed TCGObjectIdentifier

---

build.gradle

[#61] Line ending error in scripts.

---

build.gradle
scripts/windows/allcomponents.ps1
src/main/java/cli/ValidatorCli.java

Closes #65.
Fixed an exit code problem with the validator.
Fixed some other scripting typos.
Preparing for release 1.1.2r1

[#65] Validator update to the exit code

---

build.gradle
scripts/hw.sh

Small fix to not ignore disabled components.

[#79] Collect physical components which are not enabled.

---

build.gradle
scripts/allcomponents.sh
scripts/hw.sh
scripts/smbios.sh

[#84] Retrieve permanent MAC address on NICs.

---

build.gradle
scripts/windows/allcomponents.ps1
src/main/java/tcg/credential/CommonCriteriaMeasures.java
src/main/java/tcg/credential/FIPSLevel.java

Fixed issue with empty serial number string resulting in corrupted JSON data.

[#90] Fixed issue with empty serial number string resulting in corrupted JSON data.

---

README.md
build.gradle
scripts/hw.sh
scripts/windows/allcomponents.ps1

paccor attempts to collect component identifiers that are independent of OS. 
Updated the component identifier gathering scripts based on feedback.

Script updates based on feedback re Windows disk model

---

scripts/get_ek.sh

Closes #98.
Modified get_ek.sh to also work with tpm2-tools 4 to read NV public areas

[#98] Linux EK gathering will work with an updated dependency.

---

scripts/allcomponents.sh
scripts/windows/allcomponents.ps1

Added Keywords to use in scripts for the status attribute

Added JSON Status Keywords

---

dotnet/paccor_scripts/paccor_scripts/paccor_scripts.csproj
dotnet/paccor_scripts/paccor_scripts/resources/paccor.paccor_scripts.targets

Added project file properties to aid in targeting script files.

paccor_scripts .net v1.0.1

---

.github/workflows/dotnet-build-hardwaremanifest.yml
.github/workflows/dotnet-build-paccor_scripts.yml
dotnet/HardwareManifestPlugin/HardwareManifestPlugin/HardwareManifestPlugin.csproj
dotnet/HardwareManifestPlugin/HardwareManifestPlugin/src/HardwareManifestConverter.cs
dotnet/HardwareManifestPlugin/HardwareManifestPluginManager/HardwareManifestPluginManager.csproj
dotnet/HardwareManifestPlugin/HardwareManifestPluginTests/HardwareManifestPluginTests.cs
dotnet/HardwareManifestPlugin/HardwareManifestPluginTests/HardwareManifestPluginTests.csproj
dotnet/paccor_scripts/paccor_scripts/paccor_scripts.csproj
dotnet/paccor_scripts/paccor_scripts/src/PaccorComponentScriptsPlugin.cs

Also bumping up the framework target.

Rename convert class to avoid collision with System.Convert
